// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  channelId: __t.u64().name("channel_id"),
  subjectType: __t.string().name("subject_type"),
  subjectId: __t.string().name("subject_id"),
  canView: __t.bool().name("can_view"),
  canPost: __t.bool().name("can_post"),
});
