// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  slug: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  kind: __t.string(),
  difficulty: __t.string(),
  thumbnailUrl: __t.string().name("thumbnail_url"),
  embedUrl: __t.string().name("embed_url"),
  markdownBody: __t.string().name("markdown_body"),
  published: __t.bool(),
  featured: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
