// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  categoryId: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  description: __t.string(),
  kind: __t.string(),
  isArchived: __t.bool(),
  sortOrder: __t.u32(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelAccessRule = __t.object("ChannelAccessRule", {
  id: __t.u64(),
  channelId: __t.u64(),
  subjectType: __t.string(),
  subjectId: __t.string(),
  canView: __t.bool(),
  canPost: __t.bool(),
});
export type ChannelAccessRule = __Infer<typeof ChannelAccessRule>;

export const ChannelCategory = __t.object("ChannelCategory", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  description: __t.string(),
  sortOrder: __t.u32(),
});
export type ChannelCategory = __Infer<typeof ChannelCategory>;

export const DmParticipant = __t.object("DmParticipant", {
  id: __t.u64(),
  threadId: __t.u64(),
  clerkId: __t.string(),
  unreadCount: __t.u32(),
});
export type DmParticipant = __Infer<typeof DmParticipant>;

export const DmThread = __t.object("DmThread", {
  id: __t.u64(),
  userAClerkId: __t.string(),
  userBClerkId: __t.string(),
  createdAt: __t.timestamp(),
});
export type DmThread = __Infer<typeof DmThread>;

export const MemberGroup = __t.object("MemberGroup", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  description: __t.string(),
});
export type MemberGroup = __Infer<typeof MemberGroup>;

export const MemberGroupMembership = __t.object("MemberGroupMembership", {
  id: __t.u64(),
  clerkId: __t.string(),
  groupId: __t.u64(),
});
export type MemberGroupMembership = __Infer<typeof MemberGroupMembership>;

export const MemberProfile = __t.object("MemberProfile", {
  clerkId: __t.string(),
  email: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  role: __t.string(),
  subscriptionTier: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type MemberProfile = __Infer<typeof MemberProfile>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  channelId: __t.u64(),
  dmThreadId: __t.u64(),
  authorClerkId: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  isDeleted: __t.bool(),
});
export type Message = __Infer<typeof Message>;

export const Tutorial = __t.object("Tutorial", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  kind: __t.string(),
  difficulty: __t.string(),
  thumbnailUrl: __t.string(),
  embedUrl: __t.string(),
  markdownBody: __t.string(),
  published: __t.bool(),
  featured: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Tutorial = __Infer<typeof Tutorial>;

export const TutorialTag = __t.object("TutorialTag", {
  id: __t.u64(),
  tutorialId: __t.u64(),
  tag: __t.string(),
});
export type TutorialTag = __Infer<typeof TutorialTag>;

