// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  actorClerkId: __t.string(),
  tutorialId: __t.u64(),
  title: __t.string(),
  summary: __t.string(),
  kind: __t.string(),
  difficulty: __t.string(),
  thumbnailUrl: __t.string(),
  embedUrl: __t.string(),
  markdownBody: __t.string(),
  featured: __t.bool(),
};
