// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ArchiveChannelReducer from "../archive_channel_reducer";
import ArchiveTutorialReducer from "../archive_tutorial_reducer";
import AssignGroupMemberReducer from "../assign_group_member_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateDmThreadReducer from "../create_dm_thread_reducer";
import CreateMemberGroupReducer from "../create_member_group_reducer";
import CreateTutorialReducer from "../create_tutorial_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import EditOwnMessageReducer from "../edit_own_message_reducer";
import MarkThreadReadReducer from "../mark_thread_read_reducer";
import PublishTutorialReducer from "../publish_tutorial_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetChannelAccessRuleReducer from "../set_channel_access_rule_reducer";
import SyncProfileFromAuthReducer from "../sync_profile_from_auth_reducer";
import UpdateChannelReducer from "../update_channel_reducer";
import UpdateTutorialReducer from "../update_tutorial_reducer";

export type ArchiveChannelParams = __Infer<typeof ArchiveChannelReducer>;
export type ArchiveTutorialParams = __Infer<typeof ArchiveTutorialReducer>;
export type AssignGroupMemberParams = __Infer<typeof AssignGroupMemberReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateDmThreadParams = __Infer<typeof CreateDmThreadReducer>;
export type CreateMemberGroupParams = __Infer<typeof CreateMemberGroupReducer>;
export type CreateTutorialParams = __Infer<typeof CreateTutorialReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type EditOwnMessageParams = __Infer<typeof EditOwnMessageReducer>;
export type MarkThreadReadParams = __Infer<typeof MarkThreadReadReducer>;
export type PublishTutorialParams = __Infer<typeof PublishTutorialReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetChannelAccessRuleParams = __Infer<typeof SetChannelAccessRuleReducer>;
export type SyncProfileFromAuthParams = __Infer<typeof SyncProfileFromAuthReducer>;
export type UpdateChannelParams = __Infer<typeof UpdateChannelReducer>;
export type UpdateTutorialParams = __Infer<typeof UpdateTutorialReducer>;

